package org.syphr.mythtv.protocol.types;

public enum RecorderFlag
{
    FRONTEND_READY,
    RUN_MAIN_LOOP,
    EXIT_PLAYER,
    FINISH_RECORDING,
    ERRORED,
    CANCEL_NEXT_RECORDING,
    LIVE_TV,
    RECORDING,
    ANTENNA_ADJUST,
    REC,
    EIT_SCAN,
    CLOSE_REC,
    KILL_REC,
    NO_REC,
    KILL_RING_BUFFER,
    WAITING_FOR_REC_PAUSE,
    WAITING_FOR_SIGNAL,
    NEED_TO_START_RECORDER,
    PENDING_ACTIONS,
    SIGNAL_MONITOR_RUNNING,
    EIT_SCANNER_RUNNING,
    DUMMY_RECORDER_RUNNING,
    RECORDER_RUNNING,
    ANY_REC_RUNNING,
    ANY_RUNNING,
    RING_BUFFER_READY,
    DETECT;
}
